### ISSUE TITLE
accessing pagination permalink path?

### ISSUE THREAD

**Issue by Raytray** [sverrirs/jekyll-paginate-v2#10]
The original jekyll paginate implementation had a single permalink which we can access in our includes/layouts with site.paginate_path

Does jekyll-paginate-v2 provide the permalink path down?

My goal is to be able to provide a list of links: similar to the below.

Previous, 1, 2, 3, 4, 5, Next

The example files only show Previous/Next and I'm unable to generate links for 1-5 without access to the paginate_path. I can hardcode it, but that prevents me from using the same includes file for everything I want paged.

Thanks

**Comment by sverrirs** [comment]
Hi Raymond, this is a great idea! :+1: 

The implementation will be a little different due to the difference in complexity between the old gem and this new one but I'll do this.

**Comment by sverrirs** [comment]
Done, available in v1.7.0 of the gem

**Comment by emeraldjava** [comment]
@sverrirs is there an example of how we can enable this feature in a page?

**Comment by sverrirs** [comment]
@emeraldjava please consult the docs under "pagination trails" and example project  03 for the details https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#creating-pagination-trails

**Comment by justinechacko** [comment]
Do we need to count total pages always when we create new page so that we can put "before and after" in front matter. Then it is tedious.

**Comment by sverrirs** [comment]
@justinechacko Please create a new ticket for your issue and elaborate a little more on what you're trying to do.
