### ISSUE TITLE
Offset offsets posts on each page, not just first

### ISSUE THREAD

**Issue by bildungsroman** [sverrirs/jekyll-paginate-v2#100]
Hi all! I'm fairly new to Jekyll but I can't seem to find a way to fix this bug. I have a featured section on my blog that always shows the most recent post. The other posts appear below, 10 per page using paginate-v2. I tried to simply show them using `{% for post in paginator.posts offset:1 %}`, but this is flawed in two ways:
- it only shows 9 posts per page instead of 10
- it offsets each page, so that the 1st, 10th, 20th, etc. posts are hidden, which is not what I want

Am I just using `offset` wrong, or is this a bug in paginate?

Right now I've "fixed" it by doing the following, but it's not ideal as the first page only shows 9 posts:

```
    <div class="articles-showcase row post-list">
    {% assign featuredpost = site.posts.first %}
      {% for post in paginator.posts %}
      {% if post == featuredpost %}
      {% continue %}
      {% else %}
      <!-- Article Card -->
      <div class="article-detail-box col-lg-6 col-md-6 col-sm-12 card-article-div" data-cat="{{post.category | join: ','}}">
        <div class="card card-article box-shadow h-100">
          <a href="{{ site.baseurl }}{{post.url}}" class="card-article-linker" title="{{post.title}}"></a>
          <div class="img-div text-center post-card-header bg-gray">
            <img src="{{ site.baseurl }}{{post.image}}" alt="{{post.title}}">
          </div>
          <div class="card-article-body">
            <p class="author-name">{{post.author}} | {{ post.date | date: '%B %d, %Y' }}</p>
            <a href="{{site.baseurl}}{{post.url}}">
              <h5>{{post.title}}</h5>
            </a>
            <div class="article-description">{{post.content}}</div>
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
```

**Comment by rvanhorn** [comment]
Hello,

I also ran into this issue and after trying a dozen different things, nothing worked. 

So I went with a pretty basic method. :)

1. Remove offset code.
2. Run Jekyll build.
3. In _site copy category and tag folder.
4. In the latest post, add ``hidden: true`` in the front matter.
5. Run jekyll build again.
6. in _site, delete category and tag folder and replace with copied folder from before.

It's a manual solution but it works, next thing for me will be automating this part.

**Comment by bildungsroman** [comment]
@rvanhorn That's a good manual workaround, but not really feasible for me as our company blog is updated several times a week by different people. I really wish this could be fixed.

**Comment by sverrirs** [comment]
@bildungsroman Hi Anna, sorry that you've been having issues with this plugin. This should be resolved now.

I've just pushed a new gem version v2.0.0 that includes a new 'offset' feature (I actually dug this out of an old closed PR that I hadn't merged). Could you give it a spin?

The documentation for the feature is here:
https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#offsetting-posts

**Comment by bildungsroman** [comment]
@sverrirs Thank you! I'll implement it and let you know

**Comment by rvanhorn** [comment]
That worked for me, thanks @sverrirs.

**Comment by sverrirs** [comment]
Alright, I'll close this issue for now then. :)
