### ISSUE TITLE
Make autopages.display_name available to title

### ISSUE THREAD

**Issue by mmistakes** [sverrirs/jekyll-paginate-v2#11]
Is there a way to output the display name along with the page x of x string? I tried swapping page.title with page.autopages.display_name but it loses the Page :num of :max bit.

page.tag = "Foo Bar"

<title>{{ page.title }}<title> ~> <title>foo-bar - Page x of x</title>
<title>{{ page.autopages.display_name }}</title> ~> <title>Foo Bar</title>

**Comment by sverrirs** [comment]
Thanks for creating a new ticket, I will look into this as soon as I can :)

**Comment by sverrirs** [comment]
@mmistakes  OK Michael so this was much simpler feature than I had expected so I just went ahead and added it. 

The data is available under a new meta data structure for the pagination logic, the docs go into the details https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#reading-pagination-meta-information
