### ISSUE TITLE
paginated pages are not included in sitemap

### ISSUE THREAD

**Issue by XhmikosR** [sverrirs/jekyll-paginate-v2#142]
Hello.

I decided to give this a go. It works well except for the following issue: sitemap.xml does not include the paginated pages; the original jekyll-paginate does include them.

PR: <https://github.com/twbs/bootstrap-blog/pull/99>
Preview: <https://twbs-blog-paginate.netlify.com/>

**Comment by ashmaroli** [comment]
The reason for this is because pagination-pages have the `:name` attribute set to `".html"`, and `nil` as `output_ext` and therefore return `false` to the query `page.html?`

**Comment by XhmikosR** [comment]
@ashmaroli @sverrirs: this is still an issue with v2.0.0.

**Comment by ashmaroli** [comment]
`v2.0.0` was released before this ticket was opened or the patch for this was shipped, so yeah...
You may want to point your Gemfile to the `master` branch of this repo to use the patch in your site.

**Comment by XhmikosR** [comment]
But then we have the other bugs on master, or are most of them fixed? Like the `index.html` included in the `link rel=prev` tags.

**Comment by ashmaroli** [comment]
I'm not aware of that issue. I'm no longer an active-contributor of this project. So won't be able to help in that area. Sorry.

**Comment by XhmikosR** [comment]
@sverrirs this is still an issue with v3.0.0
