### ISSUE TITLE
Duplicate IDs

### ISSUE THREAD

**Issue by XhmikosR** [sverrirs/jekyll-paginate-v2#143]
This bug is present in the original jekyll-paginate gem too.

There are cases where we end up with duplicate IDs, example: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftwbs-blog-paginate.netlify.com%2F

**Comment by ashmaroli** [comment]
@XhmikosR Header-ids are generated by Kramdown. Its not within the scope of this plugin.
You'll get multiple ids even on a minimal site without any plugins..

**Comment by XhmikosR** [comment]
I don't know who's to blame, I know it happens.

**Comment by ashmaroli** [comment]
@XhmikosR I think the report is best filed at the [Kramdown](https://github.com/gettalong/kramdown) repository. Jekyll doesn't do anything regarding this AFAIK..

**Comment by XhmikosR** [comment]
Yeah, but maybe it should do? I mean, Jekyll only knows about the whole page context, not kramdown or whatever Markdown processor is being used.

**Comment by ashmaroli** [comment]
That said, you can turn-off `auto-id`s entirely by setting the following in your config file:
```yaml
kramdown:
  auto_ids: false
```

**Comment by XhmikosR** [comment]
I know, but I do like auto IDs.

**Comment by ashmaroli** [comment]
Hmm.. we're at an impasse then.
The reason why Jekyll can't do anything is because `site.posts` simply represents a bucket of all the `posts` in the site. Two posts can have the exact same content as long as they're at separate paths.
Iterating between these two posts and rendering them on the same page will result in absolute duplicate markup.
Jekyll creates `Document` instances based on path rather than their contents.

**Comment by XhmikosR** [comment]
Yeah, they can have the same content but not the same IDs. I'm still not 100% who should work around this issue, but it's definitely an issue.

That being said, I'm gonna close this issue since it's unrelated to this plugin as it seems.

**Comment by XhmikosR** [comment]
I made https://github.com/gettalong/kramdown/issues/561

**Comment by ashmaroli** [comment]
Even before you get a response from `@gettalong`, let me tell you that Kramdown generates these IDs and it has no idea whether another document is going to contain the same header tag.
I just run a test:
```
---
---

# Whats new

# Whats new

# Whats new

# Whats new
```
will generate non-identical ids.. 
So, Kramdown is in the clear..

**Comment by ashmaroli** [comment]
What we need is a HTML-linter plugin that will run through rendered HTML and make necessary corrections for us... 
:bulb:
HTMLProofer perhaps..?

**Comment by ashmaroli** [comment]
> So this brings us to my initial thought that maybe Jekyll should handle this because only Jekyll knows the context of the files that are generated.

Jekyll Core has a minimal-interference policy. It will not alter the generated HTML in any way.
You'll have to depend on plugins for that sort of functionality.

Remove redundant whitespace in your HTML? Use a plugin..
Prettify the generated HTML? Use a plugin..
Check if the generated HTML is actually valid HTML? Use a plugin..
Want a feed generated for your posts? Use a plugin..

**Comment by XhmikosR** [comment]
But this is just wrong code generation, nothing to do with checking.

**Comment by ashmaroli** [comment]
If it has nothing to do with checking and I have the following code in my page, who's to blame?
```
{% assign random_array = 'lorem,ipsum,dolor,sit,amet' | split: ',' %}
{% for item in random_array %}
  <h3 id="xmr>Hello</h5>
{% endfor %}
```

**Comment by XhmikosR** [comment]
Well, sure but this isn't custom code. This is the result with the default settings.

**Comment by ashmaroli** [comment]
My point from above example boils down to just this:
*"Jekyll does not validate markup!
It just generates files based on configuration; files which can then be collectively pushed to a remote domain where they're served as is.."*

**Comment by XhmikosR** [comment]
I never said it validates it, but it shouldn't generate invalid code, that's my point.
