### ISSUE TITLE
Wrong path in link rel prev/next

### ISSUE THREAD

**Issue by XhmikosR** [sverrirs/jekyll-paginate-v2#145]
While trying to switch to this gem in https://github.com/twbs/bootstrap-blog/pull/99, I noticed the following:

```html
<link rel="prev" href="https://blog.getbootstrap.com/index.html" />
<link rel="next" href="https://blog.getbootstrap.com/page3/index.html" />
```

This is wrong in the sense it doesn't account for the permalink setting. Using v2.1.0.

**Comment by ashmaroli** [comment]
In other words, if the global setting is `permalink: pretty`, then the expected result is:
```html
<link rel="prev" href="https://blog.getbootstrap.com/" />
<link rel="next" href="https://blog.getbootstrap.com/page3/" />
```
I believe this issue is the same even on versions older than `v2.1.0`

**Comment by ashmaroli** [comment]
That said I'm not sure if the issue is with this plugin or `jekyll-seo-tag` because the markup is a result of the following template used in `jekyll-seo-tag`:
```liquid
{% if paginator.previous_page %}
  <link rel="prev" href="{{ paginator.previous_page_path | absolute_url }}" />
{% endif %}
{% if paginator.next_page %}
  <link rel="next" href="{{ paginator.next_page_path | absolute_url }}" />
{% endif %}
```

**Comment by XhmikosR** [comment]
This is a regression in 2.1.0. With v2.0.0 it's fine here:

```
<link rel="prev" href="http://localhost:4000/" />
<link rel="next" href="http://localhost:4000/page3/" />
```

**Comment by ashmaroli** [comment]
Oh I see..
Since, `v2.1.0` is entirely composed of changes I proposed, I'm morally obligated to investigate this issue further..

**Comment by ashmaroli** [comment]
After some investigation this seems to be a result of change in https://github.com/sverrirs/jekyll-paginate-v2/commit/8d459978cc694436d881dab34599c7a6c4aec0c1

I'm not sure how exactly to proceed now. Revert that change and re-introduce the resolved issue or, find another alternative..
Feedback invited.

**Comment by XhmikosR** [comment]
I think both are real issues so ideally a proper fix should be made :)

**Comment by XhmikosR** [comment]
Any news about this? It's a regression compared to v2.0.0.

**Comment by sverrirs** [comment]
Could you please upgrade to https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0 and test again for me?

**Comment by XhmikosR** [comment]
It seems this is fixed now!
