### ISSUE TITLE
Paginating collection indexes and collection category indexes?

### ISSUE THREAD

**Issue by AndreiJosan** [sverrirs/jekyll-paginate-v2#149]
Hello!
Thanks for this amazing plugin. It works perfect for me when I use it with the _posts collection, I've achieved awesome things with it.

However, would it work in a similar way if I create a new collection, let's say "cars", which has its own categories (say "sedan", "SUV" etc). Would I be able to generate paginated indexes for all cars, for sedanes, SUVs and so on? I've tried it today but with no luck.

Thanks a lot!

**Comment by curious-toad** [comment]
This is exactly what I'm looking to do (sorry, I didn't check if there was an existing issue here first!)

Did you manage to get this working in the end?

**Comment by sverrirs** [comment]
Consider using tags
