### ISSUE TITLE
markdown content broken on page2+

### ISSUE THREAD

**Issue by benswift** [sverrirs/jekyll-paginate-v2#154]
I use the pagination gem on my blog.

On the [blog index page](http://benswift.me/blog/index.html), I have a bunch of "intro" copy. It's just regular markdown content which I include above the `{% for post in paginator.posts %} ...` part.

On [page 1](http://benswift.me/blog/index.html), everything's dandy. However, on page 2 (and page 3, etc.) that intro copy doesn't get markdownified (see [here](http://benswift.me/blog/page2/index.html)).

Have I configured things wrong?

Blog source is on GH if that helps (here's the [index page](https://github.com/benswift/benswift.github.io/blob/source/blog.md), and here's the [pagination stuff in an include file](https://github.com/benswift/benswift.github.io/blob/source/_includes/paginate.html)).

**Comment by benswift** [comment]
Hi 👋 

Nope, sadly, it doesn't help---same issue persists.

I'm currently using `v2.1.0` if that helps.

**Comment by ashmaroli** [comment]
I know that you're using `v2.1.0`. That's why I asked if *downgrading* helps.. :wink:
Will you be able to create a test repository with the minimum content that reproduces this issue?

**Comment by ashmaroli** [comment]
@benswift  The issue is not with this plugin, but rather with your set up.
`blog.md`, `livecoding.md` etc are standalone pages. They're outside this plugin's scope.

What you need to do is take either of the two routes below:
- if all "standalone" pages need to include "pagination logic", then **move  `{% include paginate.html %}`** inside `page` layout itself:
  ```
  <article>
  <h1>{{ page.title }}</h1>
  {{ content }}

  {% include paginate.html %}
  </article>
  ```
- Or if only *some "standalone" pages* need to have pagination logic included, then create a new layout and follow the instructions in the above step.

P.S. Don't forget to remove the `{% include paginate.html %}` from all the concerned "standalone" pages.

**Comment by benswift** [comment]
Hey, thanks for looking into this while I was celebrating (happy new year 🎆 btw)---you've gone above and beyond for sure.

I tried the "put the pagination into the layout" thing as you suggested, and neither option seemed to work (although I didn't look into it in detail).

What *did* work was just changing the file ext from `.md` to `.html`.  I tried this because it says that it only works for `.html` files on the [Jekyll pagination page](https://jekyllrb.com/docs/pagination/), although I was a little confused because that's referring to the paginage v1 gem, not paginate v2.

Anyway, it's now working---again, [source here](https://github.com/benswift/benswift.github.io/blob/source/blog.html) if anyone's interested in the future. Thanks for your help.

**Comment by ashmaroli** [comment]
@benswift Happy New Year to you too!! :fireworks: :smiley: 

While I'm glad that you've the issue sorted, it's sad that you had to opt for creating a `.html` file manually instead of having Jekyll convert the Markdown content for you.

**Comment by benswift** [comment]
Yeah, it could be worse. So it it still the case that the pagination object only “works” on an HTML page, for both v1 and v2 of the pagination gem?

**Comment by ashmaroli** [comment]
While v1 was very strict in having an `index.html`, the v2 is much saner.

I had the site working as expected (or did I ?) with the steps I recommended in the earlier comment.
But, I have since deleted your repo's clone and won't be cloning again (since its over 100MB) :wink:

**Comment by benswift** [comment]
Yeah, that’s fine. I should go back and debug it more thoroughly. I just got it working and said “that’ll do”, y’know?

**Comment by emma-sax4** [comment]
I have my paginated pages as markdowns. I'm on version 2.0.0. The one thing I have noticed is that on page 2+, sometimes separate markdown paragraphs won't render as separate paragraphs. Therefore, within the markdown pages, I put 
```html
<p>
  Words go here.
</p>

<p>
  Other words go here.
</p>
```

AKA by putting in the `<p></p>`, they separate properly on all pages.

**Comment by benswift** [comment]
This is a blast from the past. For reference, I eventually got it working (pagination + being able to write markdown rather than raw HTML) by putting the pagination stuff into the (HTML) layout file.

It's all here if anyone's looking for an example: <https://github.com/benswift/benswift.github.io/blob/source/_layouts/paginated.html>

**Comment by emma-sax4** [comment]
That wasn't my issue at all. What happened to me was that I write a file like this in markdown:
```markdown
---
layout: blog
permalink: /blog/welcome-to-kenya/
url_shortname: /welcome-to-kenya
pagination:
  enabled: true
  collection: posts
  permalink: /:num/
  title: Welcome to Kenya
  category: Welcome to Kenya
---

A complilation of five blog posts revolving around my trip to Kenya in the summer of 2019. You can tell I will remember Kenya with fond memories.

I'd like to extend a huge "thank you" to my fellow adventurers: Kristen Correa, Evelyn Kodman, Jennifer Hruska, Impreet Aulakh, Kristal Seckinger, Heather Hubbard, Audrey Boss, Sarah Hawkins, Tami McBride, and Linda McWilliams, for the use of their incredible photos in these posts.
```
And that renders this on the first paginated page (correctly):
![image](https://user-images.githubusercontent.com/7562793/72213876-2657b680-34bc-11ea-8c35-fc5d391c4a59.png)
And on the second page, it renders like this:
![image](https://user-images.githubusercontent.com/7562793/72213883-44bdb200-34bc-11ea-8de1-0039ca9d9ca3.png)

Notice how on the second page, the words are now part of one big paragraph, and it no longer respects the same CSS spacing. It's because on the first paginated page, the generator properly adds `<p></p>` for each paragraph, but on every paginated page after, it doesn't add those tags. The only solution is for me to add them into my markdown myself:
```markdown
<p>
  A complilation of five blog posts revolving around my trip to Kenya in the summer of 2019. You can tell I will remember Kenya with fond memories.
</p>

<p>
  I'd like to extend a huge "thank you" to my fellow adventurers: Kristen Correa, Evelyn Kodman, Jennifer Hruska, Impreet Aulakh, Kristal Seckinger, Heather Hubbard, Audrey Boss, Sarah Hawkins, Tami McBride, and Linda McWilliams, for the use of their incredible photos in these posts.
</p>
```

**Comment by benswift** [comment]
Hmm, ok. I must confess that I don't know that much about how this gem works myself; I'm not a contributor, just the person who was having the issue (which might not be the same as yours).

So do you think in your case the first page is getting markdownified, but the subsequent pages aren't? That might explain why adding the `<p>` tags manually fixes it; it's just get

I fixed the "sometimes the content isn't getting markdownified" issue by [explicitly passing the `content` through the `markdownify` filter [in my pagination layout](https://github.com/benswift/benswift.github.io/blob/source/_layouts/paginated.html#L5).

**Comment by emma-sax4** [comment]
@benswift I think that is the issue. Explicitly adding `| markdownify` totally worked!

**Comment by benswift** [comment]
Great news 😊
