### ISSUE TITLE
Posts not built on upload

### ISSUE THREAD

**Issue by ebaizel** [sverrirs/jekyll-paginate-v2#16]
first off, thanks for updating paginate for jekyll 3!

i'm running into an issue where pages are not generated when i push to github, but when i run locally, everything works fine.  on github, the feed.xml has the blog posts in there, but the index.html has none.

when i revert back to the original paginate gem it starts working again, so i thought it could be related to this paginate-v2 gem.  it's super hard to debug on github, but one thing i see locally is `AutoPages: Disabled/Not configured in site.config`.   do i need to explicitly disable AutoPages to get it to run on github?

**Comment by sverrirs** [comment]
Hi Emile,

Thank you for the kind words. Unfortunately my v2 gem is not yet supported by github. I hope it will be at some point though. Sorry.

**Comment by sverrirs** [comment]
See https://github.com/sverrirs/jekyll-paginate-v2/issues/9

**Comment by ebaizel** [comment]
Thanks for the quick response Sverrir. That makes sense.  Definitely would be great to have this supported on GitHub. Let me know if i can help in any way with that.
