### ISSUE TITLE
2.1 was yanked from ruby gems?

### ISSUE THREAD

**Issue by eddietejeda** [sverrirs/jekyll-paginate-v2#160]
I was getting the following error:

```
Fetching gem metadata from https://rubygems.org/.........
Could not find jekyll-paginate-v2-2.1.0 in any of the sources
```
When I checked out Ruby gems, I see that 2.1 was yanked. What's going on here?

<img width="716" alt="Screen Shot 2019-04-03 at 12 26 50 PM" src="https://user-images.githubusercontent.com/669988/55495931-f665b380-560b-11e9-9106-b2b6ae9f2436.png">

**Comment by ashmaroli** [comment]
@eddietejeda Yes, `v2.1.0` has been yanked since it was buggy and broke users' sites.
Please downgrade to `v2.0.0`
Apologies for the inconvenience caused.

**Comment by sverrirs** [comment]
Further rollbacks performed, please upgrade to https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0
