### ISSUE TITLE
Support and compatibility with Jekyll 4.0

### ISSUE THREAD

**Issue by rdsaunders** [sverrirs/jekyll-paginate-v2#165]
Good morning.

I've just upgraded a site locally to Jekyll 4.0 and I'm having trouble getting Jekyll-paginate-v2 to behave properly 🙁.

## Bundle update results in older version being used.

- **Given** checkout a clean repo of my site
- **and** no Gemfile.lock is present
- **When** I do a bundle update
- **Then** the jekyll-paginate-v2 version is set to 1.5.2 not the latest (2.0.0)

```
jekyll-paginate-v2 (1.5.2)
```

## Pages that have pagination enabled and don't meet the per_page count result in an error

> This error is likely to be related to the wrong version of the plugin being used.

- **Given** I have a page where pagination is enabled
- **and** the number of items is less than the per_page value set in the config
- **When** the site is served locally
- **Then** I receive an error

`Error: comparison of Jekyll::Document with Jekyll::Document failed`

When the page is removed from pagination e.g. set to false. Then the site is served and the page is rendered without any of the content.

```
pagination:
  enabled: false
```

If I can provide any more information please let me know.

Rich

**Comment by Ollymid** [comment]
The current version of jekyll-paginate-v2 (2.0.0) uses a pessimistic operator (jekyll ~> 3.0 ) which keeps any updates within the realms of Jekyll 3, so this plugin doesn't support Jekyll 4 yet. 

 I too also want to use this gem with Jekyll 4, and I have made a pull request (#167 ) to relax the Jekyll dependency requirement of this plugin, as per Jekyll's guidelines. 

I'd appreciate your support if you can,  so we can get this updated and published

**Comment by rdsaunders** [comment]
@Ollymid Thanks for taking the time to make the pull request. Hopefully @sverrirs will be able to accept the change and get things rolling.

**Comment by themeix** [comment]
Yes! its time to update jekyll-paginate-v2 for the jekyll v4.x.x

**Comment by DavidCao22** [comment]
On top of getting it ready for Jekyll 4, it'd also be really nice to get it to take over the deprecated `jekyll-paginate` gem and get it into the GitHub Pages gem (per https://github.com/sverrirs/jekyll-paginate-v2/issues/9 and https://github.com/sverrirs/jekyll-paginate-v2/issues/50)

**Comment by sverrirs** [comment]
Hi all, so I had a little while to look at this and merge. However I need to revert a bunch of commits already that polluted the now janked v2.1 release first. 

@Ollymid Thanks for taking the time to do the PR I will get this merged and released as soon as I can tonight

**Comment by Ollymid** [comment]
No problem @sverrirs - thanks for the update

**Comment by Ollymid** [comment]
@sverrirs tried updating jekyll-paginate-v2 to latest version (2.1.0) but realised that it had been yanked - is there a problem?

**Comment by sverrirs** [comment]
Jekyll 4 supported, please upgrade to https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0
