### ISSUE TITLE
01-typicalblog not displaying paginated blog entries

### ISSUE THREAD

**Issue by pkellner** [sverrirs/jekyll-paginate-v2#168]
Just running jekyll serve in that directory just shows one entry in the blog and does not paginate.  See attached picture to see both browser and project (unchanged from source control).
![typblog](https://user-images.githubusercontent.com/241170/64362733-e5a6d880-cfc3-11e9-8d76-f6f3baf62c1d.png)

**Comment by sverrirs** [comment]
Fixed in  https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0
