### ISSUE TITLE
revert "Fail gracefully instead of silently fixing urls"

### ISSUE THREAD

**Issue by mohkale** [sverrirs/jekyll-paginate-v2#178]
Could someone clarify the purpose of this commit? I much preferred the previous behaviour because it allowed one to have more customised permalinks.

Right now I've got a collection structure like:
- /posts.html
- /projects.html
- /notes/languages.html
- /notes/frameworks.html

and `jekyll-paginate-v2` paginated to these files and then I configured the permalink to be `/projects/page_:num.html` so the first page of a pagination appears one directory above the rest. This worked with 2.0.0 but now it's failing my jekyll build by saying 

```
Detected invalid url "/notes/frameworks.html" for "notes/frameworks.md"
                    Expected "/notes/" or "/notes/index.html"
```

Is there a reason to force a specific pagination structure? If the issue was the silent altering of urls, couldn't a less intrusive solution be to just log the change?

**Comment by sverrirs** [comment]
Reverted, please upgrade to https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0

**Comment by mohkale** [comment]
Will do, thnx.
