### ISSUE TITLE
Pagination for authors

### ISSUE THREAD

**Issue by bastoGrande** [sverrirs/jekyll-paginate-v2#18]
Hey again,

another problem of me is, I want to have a multi-author-blog and want to autogenerate **pages** with all articles for a specific author. I know of the autopages "optional pagination addon", but I'm not sure if this is already designed for this kind of issue. Cool would be, if this autogenerated page could include something like a description and maybe even a picture of the author.
If this is already possible, how would I do this?

Or is it one more feature request?

**Comment by sverrirs** [comment]
Hi @bastoGrande , 

This is already possible using the [AutoPages feature](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md). 

Currently there is not support for custom field pagination but you could assign each of your authors a "Category" (e.g their email or username or something like that) and then paginate on that. Althernatively you could do the same by assigning your authors with tags.

Then you can create a custom layout for each author (I'm assuming you don't have hundreds of authors) that has a customized layout for that author, e.g. picture, bio, links etc and then within that page use the pagination code. 

You can see an example of this in the Examples, especially [Example 03](https://github.com/sverrirs/jekyll-paginate-v2/tree/master/examples/03-tags) which has customized layouts for autopages (https://github.com/sverrirs/jekyll-paginate-v2/blob/master/examples/03-tags/_layouts/autopage_collection.html). Just remember to configure the layouts in the _config.yml file as well.
