### ISSUE TITLE
Markdown not being rendered

### ISSUE THREAD

**Issue by lsrdg** [sverrirs/jekyll-paginate-v2#19]
Hello,

first of all: what a great plugin! It has opened a bunch possibilities around here, thanks!

One question though: the pagination is working without any problems, but I use some markdown on the top (just a header, a quote and a paragraph), _after_ the front matter and _before_  looping. Is it a normal and expected behaviour or is it just me messing with html?

I have though about turning these markdown's sections into include files that would be in included in _layout/page.html (with an `if` statement, but that seems to be pretty counter-intuitive, since it would add a lot of verbosity (meanwhile Jekyll-paginate-v2 has just allowed me to reduce a lot of verbosity, ehe).

Thanks again and keep it going (:

**Comment by sverrirs** [comment]
Hi, thanks for the kind words and I am glad that you found the plugin useful :)

For the includes you need to use HTML (as they have the `.html` file extension) You could explicitly surround your markdown code in something that renders the Markdown for you. E.g. 
`{{ page.excerpt | markdownify }}`

But in reality when you're dealing with includes and layout files I would recommend using good old HTML.

**Comment by lsrdg** [comment]
Hi, thanks for the quick feedback and for the heads up on filters.
But my apologies, I should have explained it better:

Markdown is not being rendered on pages where the plugin acting on. 

Here is a simplified version of the situation:
* `_pages/an_example_page.md`

```
---
title: "is a frontmatter"
pagination:
  enabled: true
  category: categoryA
---

### Page header

> Some quote about the content

...and a paragraph with a couple of lines about the content below (which
is the result of Jekyll-paginate-v2's for loop. o/

```

Basically, I've tried to different approaches, 1) to include the for loop **on the markdown page** after the paragraph, and 2) in `_layout/post.html` and adding `layout: post` to the front matter. In both cases the markdown doesn't work.

Is that expected and desired?

I would rather use markdown, or else in the long run that would mean a bunch of unnecessary `_include/` files or `_data/` files. I'm _not_ requesting anything here, just would like to know if it is "normal", so I can move on to working on something that will work with and not against the plugin. I'm just looking for some plain text before the loop, that could be just plain html, markdown, liquid variable or something else. 

The [reason](https://talk.jekyllrb.com/t/paginate-page-md-filtering-by-category/372) why I got started with Jekyll-paginate-v2 is a bit more complex than the example above, but I did try this example and had the same output. Let me know if I am over complicating things too much and should just let it be. (:

**Comment by sverrirs** [comment]
Hi again,

By default I think Jekyll will only render markdown syntax on pages that have the ".md" ending.  You can however force this by using the `markdownify` filter I mentioned above in the layout files where the content is being pulled in.

But to answer your questions:

1) The pagination logic should not sit inside the content files (e.g. individual post or document files). It belongs in the layout files.

2) If you place markdown code into your layout or include files you will have to explicitly pass it through the `markdownify` filter. 

My recommendation is to keep your content (e.g. blog posts) in .md files (which will only contain markdown syntax) and everything dealing with the structure of your site in .html files (which will only include HTML syntax). 

In the Examples directory there are three examples on how to use this pagination plugin and they are all complete jekyll sites. You can download them and do a `jekyll serve` to browse it locally, make changes and see what happens. Perhaps that can help answer your questions as well.

Cheers! :)

**Comment by sverrirs** [comment]
Do you have your source available publicly? I can take a look to see if I understand your problem better if you have it here on github or something like that :)

**Comment by lsrdg** [comment]
Hi again, that's really kind of you. This issue precisaly is only in a local branch, and it is a mess. I will create another cleaner branch that reproduces this issue, that will probably happen tomorrow. It wouldn't be fair to get you into this mess. (:

I have failed again in explaining, my apollogies.

> By default I think Jekyll will only render markdown syntax on pages that have the ".md" ending.

That's why it is so weird... the page is a `.md` inside `_pages`. And just to be clear, he markdown and the Jekyll-paginate-v2 are together because `_layouts/page.html` has a  `{{ content }}` **before** the pagination loop.

Maybe the issue just disappear once I have cleaned the code. o/

Cheers! (:

**Comment by lsrdg** [comment]
Hi again @

WARNING: it looks like it is **NOT** an Jekyll-paginate-v2's issue! So, if
you don't have the time, please don't even bother. However, I'll document it here
below, maybe it helps someone else. (:

Here is a screenshot of how the page looks like with my manually implemented iteration
and _without_ the plugin:

![before-pagination](https://cloud.githubusercontent.com/assets/19675984/24649118/410a5334-1926-11e7-8a57-c4758a058134.png)

After that, I  created a [new branch](https://github.com/lsrdg/eliasrodrigo.com/tree/paginate-v2) and did a minimal installation (basic `_config.yml`):

- [ ] update `_config.yml`
- [ ] update page's front matter
- [ ] update _layouts/page.html (`paginator.posts` and `paginator.total_pages` etc)

The plugin does work. Period. Here is a screenshot of the same page:


![after-pagination01](https://cloud.githubusercontent.com/assets/19675984/24649189/83ce0abc-1926-11e7-8425-015bb573ad17.png)

The html (sidebar) is broken (which makes me believe that it is just me screwing up the
html) and the markdown is not being rendered. Note that the plugin's iteration is in 
`_layouts/page.html` (the code can be seen on the branch's link above).

Just as an experiment: here is [another branch](https://github.com/lsrdg/eliasrodrigo.com/tree/paginate-v2-02)
where the only difference is that the plugin's iteration is **not** in `_layout/page.html`,
but directly in the page itself: `_pages/researching.md`.
Here is a screenshot:

![after-pagination-iterate-in-page](https://cloud.githubusercontent.com/assets/19675984/24649197/8dd03c1a-1926-11e7-90ad-ae4ebaf94566.png)

This time, the html (sidebar) is correctly rendered (which makes me believe that I've been
_definitely_ screwing up with the html) but the markdown is still not being rendered at all.

---

That's all I have about this issue so far. And I'll definitily come back with the solution later. (:

**Comment by sverrirs** [comment]
Thanks for the detailed update and I am glad that you found a hint to where the issue lies.

Consider using `{{ content | markdownify }}` on your page.html and `{{ page.sidebar | append: '.html' | prepend: '/asides/' | markdownify }}` in your default.html to force the included content that may be markdown to be rendered as markdown.

I'll close this ticket now :)

**Comment by lsrdg** [comment]
Thanks for your great feedback! I don't really understand the relation between the plugin and `markdownify`, but still it doesn't look like a plugin's issue at all.

`{{ content | markdownify }}` did the trick! The markdown is being rendered. o/
The sidebar didn't work, but it doesn't matter, that page won't need the sidebar and the languages menu will be implemented in another way (...just need to dig into the locale's options provided by the plugin first). (:

Thanks again

**Comment by cherryleafroad** [comment]
Having to pass it through `markdownify` for includes and whatever is just fine, but if you have a main page which is in markdown, it isn't really possible to pass it through markdown
