### ISSUE TITLE
add some debugging tools

### ISSUE THREAD

**Issue by stevecrozz** [sverrirs/jekyll-paginate-v2#2]
For the most part, I had an easy time following the instructions. The one thing that caused me a bit of pain was in debugging the problem where no items were appearing in my index views. I think it would be great to have a debugging tool where I could insert {{paginator.debug}} in a layout and have jekyll-paginate-v2 emit some useful information about the pagination system. I'm not sure what all could be presented, but I'm imagining something like:
~~~
JEKYLL-PAGINATE-V2 :: BEGIN DEBUG INFO ----------------------------------------
Items in collections: 0
Items in posts: 90
Current page: 1

Configuration:
  Paginating: collection 'all' (use posts for posts)
  Items per page: 10 (0 for unlimited)
  Limit: 0 (0 for no limit)
  Locale: unspecified (other options)
  Order by: date (more help text)
  Order direction: descending (or ascending)
  Filter tags: unspecified
  Filter categories: unspecified
JEKYLL-PAGINATE-V2 :: END DEBUG INFO ------------------------------------------
~~~

That's a very cursory example of some useful info. It could be formatted better and you may have better names for things or even more helpful info that could fit in here. I think one of the most useful things to add would be some info on why there were zero items if there are zero items, at least that's what had me temporarily stuck.

**Comment by sverrirs** [comment]
@stevecrozz excellent idea, I've included it in the code. You can set the `debug:true` variable in the site config or for individual pagination pages to see detailed output for each of your pagination pages.

As an example, here is the output from example site 03
```
Pagination: Page: tags/sci-fi.md
Pagination:  Active configuration
Pagination:   Enabled:          true
Pagination:   Items per page:   2
Pagination:   Permalink:        /:num/
Pagination:   Title:            :title - page :num
Pagination:   Limit:            0
Pagination:   Sort by:          book:rank
Pagination:   Sort reverse:     false
Pagination:  Active Filters
Pagination:   Collection:       fantasy,romance
Pagination:   Category:         [Not set]
Pagination:   Tag:              Science, Fiction
Pagination:   Locale:           [Not set]
```

**Comment by stevecrozz** [comment]
Thanks! I think that will be quite helpful.

**Comment by sverrirs** [comment]
No problem, I actually added an extra feature just now to show the document counts as the filters are being applied. Could make it easier to detect where errors might be happening.
