### ISSUE TITLE
All collections using layout of first collections index found

### ISSUE THREAD

**Issue by samfoley88** [sverrirs/jekyll-paginate-v2#209]
Trying to get multiple collections to paginate I'm getting some odd behaviour where it uses the layout in the first pagination request it finds for all pages.

So for instance I have a number of different collections and for each collection I have a folder with an index that is the same name as the collection but without the underscore.
So my events collection has ```_events``` with my markdown files and ```events``` with ```index.html``` that should display that collection. I have the same for "gallery" and "results" collections.

If I only activate pagination for one collection it works fine. As soon as I activate it for more than one the generated index.html's for every collection appear to use the first one it finds (in alphabetical order).

I've tested this by renaming folders and moving the pagination using index.html's around. Whichever index.html it hits first with pagination enabled becomes the one used for all of my index.html's that have collections enabled. Even if its in the root and called something else the same thing still happens.

My index.html's have similar front matter and pagination logic which is basically:
```jekyll
---
layout: page
title: Results
pagination:
  enabled: true
  collection: results
---
    
{% for result in paginator.posts %}
    <a href="{{ result.url }}">
        <h1 class="title results">
            {{ result.title }}
        </h1>
        <h6 class="date results">
            {{ result.date | date: "%A, %B %e, %Y at %I:%M%P" }}
        </h6>
    </a>
{% endfor %}
```

Posting in the hope I'm being stupid but happy to add more details and replication steps if nobody can correct me quickly. Also can post original code to an open repo if needed as its an open source project.

**Comment by salomvary** [comment]
@samfoley88 This seems to be a caching problem when using Jekyll 4. Until the maintainers release a fix you can use one of the forks from #182 or #195 as a workaround.

**Comment by samfoley88** [comment]
@salomvary Looks good to me as a fix and definitely explains the issue, my workaround is working for me but I'll close this issue out as those pull requests will definitely fix it when they get approved.

**Comment by wrmk** [comment]
Sorry for disturbing you, but the problem still exists in the main branch.
pagination uses only the first (alphabetically ordered) index.html to display all collections in the application.
A suggestion from [this comment](https://github.com/sverrirs/jekyll-paginate-v2/pull/260#issuecomment-2276040672) helped
