### ISSUE TITLE
AutoPages collections need to be disabled manually to disable processing

### ISSUE THREAD

**Issue by gouravkhunger** [sverrirs/jekyll-paginate-v2#228]
As suggested in [Autopages documentation](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md#title-should-not-contain-pagination-macros), I omitted `collections` from the configuration to disable building pages for them.

But it didn't omit them and still looked for the default `autopage-collection.html` file.
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/46792249/146750229-6ea893b8-6309-4f07-a733-b48f6c998e01.png">

When I disable it manually then it works fine.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/46792249/146750272-3f0fb041-923c-4976-bc65-055a0f19dd67.png">

but tag configurations work fine if omitted. Maybe there's some problem in the code or the docs need to be updated?

**Comment by cherryleafroad** [comment]
Can confirm here it's by default enabled even though docs say to omit it to disable it

**Comment by gouravkhunger** [comment]
Yep, I had looked around the defaults file and got it fixed back then! Thanks for taking time to reply :)

**Comment by cherryleafroad** [comment]
Why are you closing this though? At the very worst, even if it's intended behavior (which I think it shouldn't be), the docs are wrong

**Comment by gouravkhunger** [comment]
The plugin isn't being maintained anymore, most issues and PRs are stale anyway 🤷🏻‍♂️
