### ISSUE TITLE
Extra 'index.html' is always appended to trail paths

### ISSUE THREAD

**Issue by zyv** [sverrirs/jekyll-paginate-v2#25]
Hi there,

As the trail paths have been added in this commit: da74c50, `index.html` is unconditionally appended to the paths:

https://github.com/sverrirs/jekyll-paginate-v2/commit/da74c5070d5697439aa9172267fdda9ef3ed0fa6#diff-e42037a81bce954b06ea974c84446637R77

This is annoying when chosen scheme is `/:num/`. Is there any reason why this can't be removed? If it can, then I can prepare a pull request. My current solution is to resort to the `remove` liquid filter...

Many thanks!

**Comment by sverrirs** [comment]
Hi Yury, please feel free to expand on the logic to handle different permalink structures, it would be most welcome :)

**Comment by sverrirs** [comment]
Sorry for the delay, this issue has been fixed in v1.8.0 of the gem.
https://rubygems.org/gems/jekyll-paginate-v2/versions/1.8.0

**Comment by zyv** [comment]
Hi @sverrirs, thank you very much for taking care of this! We've just upgraded to the latest version, and I can confirm that it's working as expected now and I was able to remove the workaround. Cheers! :)
