### ISSUE TITLE
Does Multi-language support ?

### ISSUE THREAD

**Issue by bstarr322** [sverrirs/jekyll-paginate-v2#26]
Hi there,

Is this plugin compatible with this plugin ?
https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

I look forward to your quick reply.

Thanks,

**Comment by sverrirs** [comment]
Hi @bstarr322 

Unfortunately I have not done any special work on cross compatibility with the mentioned plugin.

Cheers :)
