### ISSUE TITLE
Need assistance - Clicking on individual paginate page breaks the path

### ISSUE THREAD

**Issue by jdwcode** [sverrirs/jekyll-paginate-v2#27]
First, I would like to say thank you very much for making the updated gem and keeping the pagination for Jekyll alive. I'm new to Jekyll and I've been able to design my blog exactly how I want it to but pagination is giving me a hard time and I been banging my head for the last two weeks trying to figure out why my pages are breaking when I click on a specific page besides page 1. 

I'm a intermediate programmer and trying to wrap my head around how pagniation works and even though I don't thorough understand how it works even after spending 3 days reading about it I was able to get the pagination working using your gem, but I'm getting more confused trying to fix the individual page breaking.  I know it should just be a few lines of codes to fix it, .

I've successfully enable pagniation on the index.html page that I wanted and the Prev, Next, and page 1 buttons work just fine, but if I decided that I wanted to go from Page 4 directly to Page 2 by clicking on Page 2 button it breaks. Or from any other pages to another page beside page 1 it breaks. What code do I need to add to enable the individual pages to pick up the path correctly?  Thanks in advance....I'm currently using the default code from Jekyll website:

{% if paginator.total_pages > 1 %}
<div class="pagination">
     {% if paginator.previous_page %}
       <a href="{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}">&laquo;   Prev</a>
  {% else %}
    <span>&laquo; Prev</span>
  {% endif %}

  {% for page in (1..paginator.total_pages) %}
    {% if page == paginator.page %}
      <em>{{ page }}</em>
    {% elsif page == 1 %}
      <a href="{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}">{{ page }}</a>
    {% else %}
      <a href="{{ site.paginate_path | prepend: site.baseurl | replace: '//', '/' | replace: ':num', page }}">{{ page }}</a>
    {% endif %}
  {% endfor %} 

 
  {% if paginator.next_page %}
    <a href="{{ paginator.next_page_path | prepend: site.baseurl | replace: '//', '/' }}">Next &raquo;</a>
  {% else %}
    <span>Next &raquo;</span>
  {% endif %}
</div>
{% endif %}

Here is the path I have my pagination code on:
![1](https://user-images.githubusercontent.com/24450693/27615514-5fed3958-5b6e-11e7-93b2-225a57a69e85.PNG) 

![2](https://user-images.githubusercontent.com/24450693/27615535-72286e62-5b6e-11e7-8d7e-e245d0ace9f1.PNG)

Below image is what happen when clicking on any other page beside page 1
![3](https://user-images.githubusercontent.com/24450693/27615544-88d328be-5b6e-11e7-8616-c28bc3de0d48.PNG)

**Comment by sverrirs** [comment]
Hi Josh, 

Sorry that you're having issues with the pagination. I know it all too well how frustrating it can be at times to deal with some aspects of Jekyll :) 

Have you had a chance to look at the example projects that come with the code? 

Example 3 might give you some answers, particularly this layout which uses the pagination trails. 
https://github.com/sverrirs/jekyll-paginate-v2/blob/master/examples/03-tags/_layouts/home.html

Cheers!

**Comment by jdwcode** [comment]
Hello Sverrir,

Good news!...... the link that you provided me is exactly what I needed and it fixed the issue quickly. I've read over the documentation 3-4 times, but I guess I didn't connect the dots together or I've overlooked the solution.

Once again, thank you very much for keeping the pagination for Jekyll alive by updating it and adding new functionality in it. Also, thank you for your very quick response to my issue I really do appreciate everything and now I can finish putting the final touches on my blog :-)

**Comment by sverrirs** [comment]
Thank you for the kind words. I'm glad that this solved your problem. 
Good luck with your blog :)
