### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by rdricco** [sverrirs/jekyll-paginate-v2#3]
I'm receiveing this message when no pagination page found. The instruction is to put a `paginate` filed on front matter instead of `pagination`.

```
 Pagination: Starting
        Pagination: Is enabled, but I couldn't find any pagination page. Skipping pagination. Pages must have 'paginate: enabled: true' in their front-matter for pagination to work.
        Generating: Jekyll::PaginateV2::Generator::PaginationGenerator finished in 0.002 seconds.
```

**Comment by sverrirs** [comment]
Ah good eye @rdricco I've fixed this issue and it will be included in the v1.6.0 version of the gem. Thanks for reporting it :+1:
