### ISSUE TITLE
Pagination with TagGenerator

### ISSUE THREAD

**Issue by jmorais** [sverrirs/jekyll-paginate-v2#31]
I'm currently using the following code to generate a page for all my tags:

```ruby
module Jekyll
  class TagIndex < Page
    def initialize(site, base, dir, tag)
      @site = site
      @base = base
      @dir = dir
      @name = 'index.html'
      self.process(@name)
      self.read_yaml(File.join(base, '_layouts'), 'tag_index.html')
      self.data['tag'] = tag
    end
  end

  class TagGenerator < Generator
    safe true
    def generate(site)
      if site.layouts.key? 'tag_index'
        dir = site.config['tag_dir'] || 'tag'
        site.tags.keys.each do |tag|
          write_tag_index(site, File.join(dir, tag), tag)
        end
      end
    end
    def write_tag_index(site, dir, tag)
      index = TagIndex.new(site, site.source, dir, tag)
      index.render(site.layouts, site.site_payload)
      index.write(site.dest)
      site.pages << index
    end
  end
end
```

This code will generate `/:tag-name/index.html` for each tag on the site. So I get something like:

- /tags/tag1/index.html
- /tags/tag2/index.html
- /tags/tag3/index.html

What I'm trying to do is to paginate each of these indexes, to get something like:

- /tags/tag1/index.html
- /tags/tag1/page/2/index.html
- /tags/tag2/index.html
- /tags/tag2/page/2/index.html
- /tags/tag2/page/3/index.html
- /tags/tag3/index.html

Any help you can provide to achieve this?

**Comment by sverrirs** [comment]
Consider using the autopage feature the gem supports.
