### ISSUE TITLE
hidden:true does not seem to hide posts from paginator.posts

### ISSUE THREAD

**Issue by assumptionsoup** [sverrirs/jekyll-paginate-v2#32]
I might be reading the documentation wrong, but [this](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#page-configuration) seems to imply that paginator.posts should not contain hidden posts.  Or is this saying that other counters like `paginator.total_pages` won't count hidden pages even though `paginator.posts` will contain them?

**Comment by sverrirs** [comment]
Hi Jordan, 
Indeed the posts that contain 
```
hidden: true
```
in their front matter should be excluded in the pagination. Is this not the case for you?

**Comment by assumptionsoup** [comment]
No, hidden posts are still in `paginate.posts`.  Here is the front matter to one of the hidden posts:
```
---
id: 91
title: Good Parenting
date: 2010-03-06T09:06:54+00:00
author: Jordan Hueckstaedt
layout: post
guid: http://rubberguppy.com/?p=91
permalink: /good-parenting/
hidden: true
dsq_thread_id:
  - "582132403"
categories:
  - scripts
---
```

And this is the template I'm using to paginate the posts:
```
<ul class="post-list">
  {% for post in paginator.posts %}
    <li class "post-list-item">
      {% assign date_format = site.minima.date_format | default: "%b %-d, %Y" %}

      <h2>
        <a class="post-link" href="{{ post.url | relative_url }}">{{ post.title | escape }}</a>
      </h2>
      <div class="post-meta">{{ post.date | date: date_format }}</div>
      <div class="post-excerpt">
          hidden: {{ post.hidden }}

          {{ post.excerpt }}
      </div
    </li>
  {% endfor %}
</ul>
```
It also shows the hidden status, because I was testing that.

**Comment by assumptionsoup** [comment]
Just searching the code-base, it looks like hidden is only considered if you're using a [legacy config](https://github.com/sverrirs/jekyll-paginate-v2/blob/8fc336f992e0bfd7bc29f39af8c6adfae6758ea0/lib/jekyll-paginate-v2/generator/paginationGenerator.rb#L126):
```
if( default_config['legacy'] ) #(REMOVE AFTER 2018-01-01)
  Jekyll.logger.warn "Pagination:", "You are running jekyll-paginate backwards compatible pagination logic. Please ignore all earlier warnings displayed related to the old jekyll-paginate gem."
  all_posts = site.site_payload['site']['posts'].reject { |post| post['hidden'] }
  model.run_compatability(default_config, all_pages, site_title, all_posts) #(REMOVE AFTER 2018-01-01)
else
  count = model.run(default_config, all_pages, site_title)
  Jekyll.logger.info "Pagination:", "Complete, processed #{count} pagination page(s)"
end
```

I think [`get_docs_in_collections`](https://github.com/sverrirs/jekyll-paginate-v2/blob/9fe7e3f0420d53a8610a963133907c566b23b424/lib/jekyll-paginate-v2/generator/paginationModel.rb#L107) should filter out hidden posts.  I don't know ruby, but I could probably take a stab at this.

**Comment by sverrirs** [comment]
Ah you're probably right, seems like a regression bug on my part. If you have the time I would be happy to accept a pull request for a fix :)

**Comment by assumptionsoup** [comment]
PR is in!

**Comment by sverrirs** [comment]
Excellent! Thanks for the help :)
