### ISSUE TITLE
migrating from jekyll-paginate to v2 with a bundle theme

### ISSUE THREAD

**Issue by douglangille** [sverrirs/jekyll-paginate-v2#37]
Using minimal-mistakes gem theme and trying to move to jekyll-paginate-v2. This theme uses jekyll-data to populate defaults in _config.yml. I should be able to wipe out the theme's values with:

```
paginate: nil
paginate_path: nil
```

This does not seem to do the trick. Jekyll build throws the following:

`Config Warning: The `paginate` key must be a positive integer or nil. It's currently set to 'nil'.`

Default values keep  pushing through as if jekyll-paginate-v2 doesn't read the nil correctly.

Any workaround or fix?

Reference issue: https://github.com/mmistakes/minimal-mistakes/issues/1240

**Comment by sverrirs** [comment]
Hi Doug,

Sorry to hear that you're having issues with the gem. However the error message you mention doesn't seem to originate from the paginate-v2 gem.

The paginate-v2 gem listens for a non nil value in the legacy settings and runs the legacy code in that case. 
https://github.com/sverrirs/jekyll-paginate-v2/blob/master/lib/jekyll-paginate-v2/generator/paginationGenerator.rb#L28

Try this:
If you run jekyll with the `--verbose` switch, do you see the message `"Pagination: Starting"` being printed? This is an indication that the  paginate-v2 code is being run. If the error is thrown before this line is seen then the issue lies with something else, if it shows up after then let me know and I will dive into the issue further.

Cheers!
Sverrir S.

**Comment by douglangille** [comment]
The original error message I received was:
```
Pagination: You are running jekyll-paginate backwards compatible pagination logic. Please ignore all earlier warnings displayed related to the old jekyll-paginate gem. 
Pagination: Detected legacy jekyll-paginate logic running. Please update your configs to use the jekyll-paginate-v2 logic. This compatibility function will stop working after Jan 1st 2018 and your site build will throw an error.
```

My attempt at disabling jekyll-paginate was to configure _config.yml:
```
paginate: nil
paginate_path: nil
```
Which is where I ended up flagging whether jekyll-paginate-v2 understood a nil setting.

Perhaps there is a way to 'force' jekyll-paginate-v2 to ignore the legacy config? That would address my issue as well.

**Comment by sverrirs** [comment]
Let me try this on my end, I'm really surprised that setting the values to nil don't trigger the new code. It might take me a few days to find time to spend on this. Hope you are alright with a few days wait :)

**Comment by douglangille** [comment]
totally cool with waiting.

Thanks for taking a look

**Comment by sverrirs** [comment]
Looking at this closer this error is actually coming from jekyll itself https://github.com/jekyll/jekyll/blob/master/lib/jekyll/configuration.rb#L255 as it is trying to do validation on these pagination keys. I've asked the Jekyll core team to reconsider this code in the Jekyll core https://github.com/jekyll/jekyll/issues/6391

**Comment by sverrirs** [comment]
_However regarding setting the old paginate values explicitly to nil_

The paginate-v2 code already handles this case and the warning that is printed out can be safely ignored. 

When setting my config file to include
```
# Explicitly turn off the old code
paginate: nil
paginate_path: nil
```

and then running `jekyll build`

I get this print out (includes the warnings) but the output in the resulting site\ folder looks good.
```
Configuration file: E:/git/jekyll-paginate-v2/examples/01-typicalblog/_config.yml
    Config Warning: The `paginate` key must be a positive integer or nil. It's currently set to '"nil"'.
    Config Warning: The `paginate` key must be a positive integer or nil. It's currently set to 'nil'.
            Source: E:/git/jekyll-paginate-v2/examples/01-typicalblog
       Destination: E:/git/jekyll-paginate-v2/examples/01-typicalblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
                    done in 0.45 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

I am afraid I need to hand you back over to the @mmistakes theme builder as it looks like this issue needs resolving on his end.

**Comment by sverrirs** [comment]
I'm closing this issue now but if there are further developments don't hesitate re-opening it and pinging me again :)

**Comment by douglangille** [comment]
Thanks for the work on this. Nothing is as simple as it seems.
