### ISSUE TITLE
Filter by category and lang?

### ISSUE THREAD

**Issue by borisschapira** [sverrirs/jekyll-paginate-v2#40]
Hi! First of all, let me thank you for the work you've done with this plugin. It is by far the more easy plugin I have used for monthes with Jekyll in order to accomplish my blog's pagination and I have never been this close to accomplish my objectives.

I try to use the pagination with both cateogies and lang. For example, having an index for the "cars" category with only the english posts, and another for the "cars" category with only the french posts. Can I do that with the plugin?

**Comment by sverrirs** [comment]
Try this
https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#filtering-locales

**Comment by borisschapira** [comment]
What a quick answer, thanks, it works!
Again, great job.
