### ISSUE TITLE
extensionless pagination links

### ISSUE THREAD

**Issue by hosnas** [sverrirs/jekyll-paginate-v2#41]
Is there any support for extensionless pagination links? How?

Right now when I use `paginator.next_page_path` or `paginator.previous_page_path` , with whatever permalink style, I would get `.html` at the end of the link.

**Comment by sverrirs** [comment]
Currently due to a decision made due to technical limitations the extension less feature does not work. This would require a little bit of work to enable again. Feel free to push a PR if you would like to make an attempt at implementing. :)

**Comment by jcbpl** [comment]
This seems to be a regression between 1.8.2 and 1.9.0. 😕

**Comment by sverrirs** [comment]
Oh, I will take a look as soon as I can (I'm on holiday at the moment)

**Comment by zyv** [comment]
Also hit by this one while attempting to update from 1.9.0 and get spammed with

```
Appending default index+ext: /news/index.html
Appending default paginated index+ext: /news/:num/index.html
```

**Comment by ibrado** [comment]
Right now, I just do something like
```
  {{ paginator.next_page_path | replace: 'index.html', '' | prepend: site.baseurl }}
```

:-D

**Comment by ibrado** [comment]
I've been looking at the `paginator.rb` source code, and I can't figure out why lines [34-50](https://github.com/sverrirs/jekyll-paginate-v2/blob/89caed0327352e9e476c1cf0999462e508475690/lib/jekyll-paginate-v2/generator/paginator.rb#L34) have to be there. The `previous`/`next_page_path` and generated pages/URLs seem to work great without those... 😕 Hmm.

**Comment by sverrirs** [comment]
Hi Alex, those lines are in there so that we can correctly deal with non-html pages (e.g. json files etc, see example 4 for more info). Extensionless is not a very simple thing as the default page is many times dependant on the webserver configuration as well. But perhaps a "smart default" value for both `default_indexpage` and `default_ext` would be in order to make sure that unnecessary default index pages aren't generated when not needed.

**Comment by ibrado** [comment]
I guess if the next/previous page paths are the primary concerns, the `replace` stuff above should work well enough...

**Comment by ibrado** [comment]
Would the following pseudocode work for the "smart default"..?
```
permalink = config['permalink'] || "/:num/"
orig_ext = extension of original filename

if default_indexpage && default_ext
  filename = "#{default_indexpage}.#{default_ext}"

elsif default_ext
  if permalink ends in / # e.g. /page:num:of:max/, 
    filename = "index.#{default_ext}"
  else # e.g. /page:num:of:max
    filename = e.g. "page1of3.#{default_ext}"
  end

elsif default_indexpage
   ext = orig_ext || "html"
   filename = "#{default_indexpage}.#{ext}"

else # neither was supplied
   ext = orig_ext || "html"
   filename = "index.#{ext}"
   remove_from_path_keys = filename
end

... before returning,

  if remove_from_path_keys
   for each paginator path key do
     paginator[key].gsub!(remove_from_path_keys)
   end
  end
```

**Comment by sverrirs** [comment]
Fixed in gem https://rubygems.org/gems/jekyll-paginate-v2/versions/1.9.2

**Comment by sebastianw** [comment]
Hello,

this still occurs for the `page_trail` feature. `trail.path` still appends index.html to the path. Fixed it by using the workaround mentioned above.

**Comment by Tensho** [comment]
Confirm, the problem is still there.
