### ISSUE TITLE
Autopage title doesn't include site name

### ISSUE THREAD

**Issue by antgel** [sverrirs/jekyll-paginate-v2#42]
Hi, I just got started with this gem - thanks!

I use autopages for my collection pagination generation. All works fine, apart from that the title of the page using `:coll` only includes the collection name. I guess this is a feature, not a bug, but is there a way to let it include the main site title? For example, my site title is FooBar, my collection is Books. I want the title attribute to read "Foobar - Books" (or similar). Any way to do this?

EDIT: I'm talking about the HTML `<title>` attribute, not as per `my_page.title`, as seen in `header.html` in the examples. It would be superfluous inside `my_page.title`... I suspect this is in some way a stupid question, but I'd like to hear what you think. :)

**Comment by sverrirs** [comment]
I would think that if you set your autopage template page to have the title the same as the site.title then it should work just fine. 
For other title related macros see https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#formatting-page-titles

**Comment by antgel** [comment]
When you say "autopage template page" do you mean for example `autopage_collection.html`? Because the `<title>` tag isn't set there, it's set earlier on by `_includes/head.html` (I'm using minima.)

I have:
```
collections:
  books:
    output: true

pagination:
  enabled: true
  debug: true
  per_page: 6
  permalink: '/:num/'
  title: ':title | :num of :max'

autopages:
  enabled: true

  collections:
    title: ':coll'
```

The first `title:` works as intended for non-autogenerated pages. But, for collections, `:coll` misses out the site title, and changing it to `title: ':title | :coll` obviously doesn't work. What did I miss?

**Comment by sverrirs** [comment]
Hmm, I will have to take a better look at this. Give me a few days to find some free time :)

**Comment by ibrado** [comment]
Hi @antgel .. Is this still an issue for you? The current minima uses Jekyll SEO Tag, which lists among its features "Page title, with site title or description appended".

I did make a small patch that I think does what you're describing here, i.e. `title: ':title | :coll'`. Perhaps you'd like to test it?

``` ruby
gem "jekyll-paginate-v2", :git => "https://github.com/ibrado/jekyll-paginate-v2.git", :branch => "autopage-title"
```

**Comment by antgel** [comment]
@ibrado Indeed, since upgrading to minima 2.3.0, things seem to behave as intended. Thanks for the ping. :)
