### ISSUE TITLE
Any updates on being supported by github pages?

### ISSUE THREAD

**Issue by ljvmiranda921** [sverrirs/jekyll-paginate-v2#46]
Hi @sverrirs , 

I would like to thank you for this wonderful plugin. It's intuitive and very powerful. However, I'm just wondering if there are any updates for this being supported in Github pages? 

Thank you so much! 

cc: @parkr

**Comment by sverrirs** [comment]
Hi @ljvmiranda921 and thank you for the kind words. The adoption by github is up to the jekyll core team/github staff so the best place would be to petition them to look into the matter.

However, deciding to support this or any other plugin would be a considerable commitment for the team at github though so it is not unreasonable for them to be hesitant. :)

**Comment by ljvmiranda921** [comment]
I see and understand. Also, thank you for being a friendly and helpful repository owner. I will close this now as well 👍
