### ISSUE TITLE
Previous / Next post

### ISSUE THREAD

**Issue by pauldijou** [sverrirs/jekyll-paginate-v2#5]
Is there a way to have a paginator inside each post? Or inside their common layout? I would like to add a `Previous` and `Next` button on each post but couldn't find a way to do so. Otherwise, really cool plugin, autopages are super useful.

**Comment by sverrirs** [comment]
Hi Paul, 

Thanks for the kind words I'm glad that you found the pagination gem useful.

Regarding next/prev links in the post page itself this feature is already supported by Jekyll. You can use the `page.next.url` and `page.previous.url` inside your post layout file to read these values.

Example:
```
<ul class="pager">
    {% if page.next.url %}
    <li class="previous">
        <a href="{{ page.next.url | prepend: site.baseurl | replace: '//', '/' }}" data-toggle="tooltip" data-placement="top" title="{{page.next.title}}">&larr; Newer</a>
    </li>
    {% endif %}
    {% if page.previous.url %}
    <li class="next">
        <a href="{{ page.previous.url | prepend: site.baseurl | replace: '//', '/' }}" data-toggle="tooltip" data-placement="top" title="{{page.previous.title}}">Older &rarr;</a>
    </li>
    {% endif %}
</ul>
```
