### ISSUE TITLE
No index.html is generated if there are no posts = 404

### ISSUE THREAD

**Issue by ibrado** [sverrirs/jekyll-paginate-v2#52]
If jekyll-paginate-v2 is enabled and there are no posts (e.g. a fresh site) or all the posts are `hidden: true`, an `index.html` will not be generated at all (unlike when it is disabled). This makes hosting services like GitHub or GitLab Pages return a 404 on the homepage URL, e.g. domain name.

Expected result: the page is still rendered, but with no items in it.

**Comment by sverrirs** [comment]
Hi Alex, if you disable the pagination plugin does an empty index page get generated?

**Comment by ibrado** [comment]
Yes it does.

**Comment by ibrado** [comment]
Turns out the fix was easy enough... :-D
