### ISSUE TITLE
Strip .html from the paginated pages (/articles/page2.html) to (/articles/page2/

### ISSUE THREAD

**Issue by shawnolson-fp** [sverrirs/jekyll-paginate-v2#56]
I'm using pagination but am pointing it to an "articles" page, not index.html in root. I've created an "articles" folder and added a new index.html to that folder (acting as the blog page). 

My permalink settings are 
permalink: /:num/ (I've also tried /:num and /articles/:num)

and my link in the page is {{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}

Everything works great except it adds a .html extension to all the pages - which results in duplicate content, since there are the same two pages at /articles/page2.html and /articles/page2/

Any assistance is much appreciated

**Comment by shawnolson-fp** [comment]
Nevermind, I see there are already a few concerns about this. 

Looks like the fix as of now is adding {{ paginator.next_page_path | replace: 'index.html', '' | prepend: site.baseurl }} to the index page.

Thanks,
Shawn - [fencepencil](https://fencepencil.com)

**Comment by sverrirs** [comment]
Fixed in gem https://rubygems.org/gems/jekyll-paginate-v2/versions/1.9.2

**Comment by shawnolson-fp** [comment]
Works perfectly, thank you so much!!!

Shawn - [fencepencil](https://fencepencil.com)
