### ISSUE TITLE
Refactor for better maintainability [dev]

### ISSUE THREAD

**Issue by ashmaroli** [sverrirs/jekyll-paginate-v2#57]
**IMO**, the current codebase requires some serious refactoring to improve maintainablity.
- [ ] Use shorter Lines of Code, consistently.
       Currently, some lines are miles long.. e.g. https://github.com/sverrirs/jekyll-paginate-v2/blob/ebdd42f13fb285c3d7ca02a0e90d8229983b47ed/lib/jekyll-paginate-v2/generator/paginationGenerator.rb#L26-L36

- [ ] Break up large functions / methods into smaller manageable (private) methods
       e.g. [PaginationGenerator.rb#generate](https://github.com/sverrirs/jekyll-paginate-v2/blob/ebdd42f13fb285c3d7ca02a0e90d8229983b47ed/lib/jekyll-paginate-v2/generator/paginationGenerator.rb#L21-L138) runs from `L21-L138`

- [ ] Use faster `Enumerable#each` and similar instead of `for..in` loops
- [ ] Prefer using `private` keyword instead of using leading underscores in method names. e.g. https://github.com/sverrirs/jekyll-paginate-v2/blob/ebdd42f13fb285c3d7ca02a0e90d8229983b47ed/lib/jekyll-paginate-v2/generator/paginationModel.rb#L127-L141

**Comment by ashmaroli** [comment]
Since this project adheres to semver principles, the last bullet-point can be reconsidered to have the methods with leading underscores placed at the bottom of the class..

**Comment by sverrirs** [comment]
I am closing this issue as it pertains more to personal code style than an  actual issue with the functionality of the gem.
