### ISSUE TITLE
AutoPages appends "index.html" to next-page links

### ISSUE THREAD

**Issue by praveenv253** [sverrirs/jekyll-paginate-v2#65]
I recently updated `jekyll-paginate-v2` from v1.8.1 to v1.9.0, and since then, I've been seeing many many occurrences of the following message when I run `jekyll serve` or `jekyll build`:

```
Appending default index+ext: /tags/kcachegrind/index.html
Appending default paginated index+ext: /tags/kcachegrind/page/:num/index.html
Appending default index+ext: /tags/deadlock/index.html
Appending default paginated index+ext: /tags/deadlock/page/:num/index.html
Appending default index+ext: /tags/logging/index.html
Appending default paginated index+ext: /tags/logging/page/:num/index.html
...
```

I realized that what this message is essentially telling me is that wherever I use the following liquid tag, AutoPages ends up appending `index.html` to the path.

``` liquid
{{ paginator.next_page_path | absolute_url }}
```

In other words, `/tags/logging/page/2/` becomes `/tags/logging/page/2/index.html`.

I think this is a bug, since links look much nicer without `index.html`, and since this wasn't happening before the update.

PS: Thank you so much for this absolutely wonderful plugin, and for the excellent documentation and examples! It fully deserves to be the next default paginator for jekyll.

**Comment by ibrado** [comment]
Hi! Please see #41

**Comment by praveenv253** [comment]
@ibrado Aha! Thanks, I completely missed that! I'm closing this issue as a duplicate then.

**Comment by sverrirs** [comment]
Fixed in gem https://rubygems.org/gems/jekyll-paginate-v2/versions/1.9.2
