### ISSUE TITLE
Output file not getting created at all when paginated collection has 0 items or filters to 0 items

### ISSUE THREAD

**Issue by Ketrel** [sverrirs/jekyll-paginate-v2#67]
My issue is that if the `tag: <tagname>` entry results in zero items, the page isn't generated at all. 

Rather than getting a page where paginator.posts is empty, the html file isn't generated at all. Is there any way around this?

**Comment by Ketrel** [comment]
Here's a repo that should showcase the issue,
https://github.com/Ketrel/paginatev2failcase

(It's not limited to filtering tags, it happens any time the paginate finds zero items)

**Comment by ibrado** [comment]
Hi. This should already be fixed in master, see #52

**Comment by Ketrel** [comment]
I had to do it a bit differently in my setup, but I can confirm that this is fixed in master.

**Comment by sverrirs** [comment]
Changes published in gem v1.9.1 https://rubygems.org/gems/jekyll-paginate-v2/versions/1.9.1
