### ISSUE TITLE
aginationIndexer.rb:30:in `block (2 levels) in index_posts_by': undefined method `downcase' for 2005:Fixnum (NoMethodError)

### ISSUE THREAD

**Issue by emeraldjava** [sverrirs/jekyll-paginate-v2#7]
I recently updated my site [https://github.com/emeraldjava/emeraldjava.github.io](https://github.com/emeraldjava/emeraldjava.github.io) to jekyll 3, the content of my Gemfile is

`source 'https://rubygems.org'

gem 'jekyll', '3.3.1'

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate-v2'
  gem 'jekyll-gist'
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jemoji'
end
`

My _config.yml file contains and there is no "theme" setting in the config

`# Plugins
gems:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
`

but and run i run my site locally using "bundle exec jekyll serve -t" i get this stack trace

`/var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationIndexer.rb:30:in `block (2 levels) in index_posts_by': undefined method `downcase' for 2005:Fixnum (NoMethodError)
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationIndexer.rb:29:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationIndexer.rb:29:in `block in index_posts_by'
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationIndexer.rb:15:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationIndexer.rb:15:in `index_posts_by'
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:61:in `block in run'
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `run'
        from /var/lib/gems/2.3.0/gems/jekyll-paginate-v2-1.6.0/lib/jekyll-paginate-v2/generator/paginationGenerator.rb:129:in `generate'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/site.rb:174:in `block in generate'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/site.rb:172:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/site.rb:172:in `generate'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/site.rb:68:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/command.rb:26:in `process_site'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/commands/build.rb:63:in `build'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/commands/build.rb:34:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/exe/jekyll:13:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
`

I appreciate this probally isn't a bug with the 'jekyll-paginate-v2' code but can you advise on how i can futher debug the isses?

**Comment by sverrirs** [comment]
Hi @emeraldjava thanks for reporting this issue. It is indeed a minor bug related to when the input is a pure numerical value. E.g. in your case "2005" is interpreted automatically as a number and not as a string. 
I will issue a fix asap and a new gem version.

**Comment by sverrirs** [comment]
Fixed in [v1.6.1](https://rubygems.org/gems/jekyll-paginate-v2/versions/1.6.1)
