### ISSUE TITLE
Generator order when generating collections?

### ISSUE THREAD

**Issue by fxedel** [sverrirs/jekyll-paginate-v2#8]
Hey, we're trying to develop a [Jekyll plugin](https://gitlab.com/fdroid/jekyll-fdroid/merge_requests/1/diffs) for the [F-Droid website](http://f-droid.org) which creates a lot of Jekyll pages that belong to the collection "apps". Now we want to make a paginated list of these apps:

```
---
layout: page
title: Browse
permalink: /packages/
pagination:
  enabled: true
  debug: true
  collection: apps
  per_page: 30
  permalink: '/:num/'
  sort_field: 'title'
  title: ':title'
---

{% for app in paginator.posts %}
  {% include app-list-item.html app=app %}
{% endfor %}
```

This code has already successfully been tested with pre-generated files for each page. But now, when generating these pages with a plugin, our generator takes very long and and the paginate generator does his job when the pages haven't been created yet. So, is there a possibility (and if not, this might be a feature request) to tell the paginate generator to basically run later, when all the other generators have already finished?

**Comment by fxedel** [comment]
Maybe I should have read your code first. `priority :highest` solved the problem.

**Comment by sverrirs** [comment]
@fxedel glad that you sorted it out yourself and thank you for posting the solution. I will update the documentation to mention this.

**Comment by kshitijb** [comment]
Hey @sverrirs. Did you update the documentation to mention this? I couldn't find it.
