### ISSUE TITLE
Pagination not working on github pages even site builded locally

### ISSUE THREAD

**Issue by s1lviu** [sverrirs/jekyll-paginate-v2#82]
Hello!

Tried to build site locally as @sverrirs [said] (https://github.com/sverrirs/jekyll-paginate-v2/issues/9#issuecomment-275615006) and push `_site` but pagination didn't work.

http://s1lviu.github.io/
https://github.com/s1lviu/s1lviu.github.io

**Comment by sverrirs** [comment]
What doesn't work? Are the pagination pages created, does the pagination code get executed? Have you tried turning on the debugging `debug:true` in the front matter?

**Comment by coolbrg** [comment]
I was facing the same issue and then saw this issue and disappointed. 
It is really nice to have.

Right now I have to content myself with `jekyll-paginate`, [Commit ID](https://github.com/coolbrg/coolbrg.github.io/commit/42f51784bd1763e21660349bd94228d42feccadc). 

https://coolbrg.me/blogs/

## When using jekyll-paginate-v2
<img width="1283" alt="Screenshot 2019-05-06 at 6 09 05 AM" src="https://user-images.githubusercontent.com/1132451/57203878-42bd5e00-6fd3-11e9-85c2-69e672bbf68e.png">
