### ISSUE TITLE
Does it work on github?

### ISSUE THREAD

**Issue by heshuhua** [sverrirs/jekyll-paginate-v2#85]
Thanks for great work.  I am a newbie in jekyll
I have a question, the paginate-v2 works fine on local server, 
But when I push to my github account, It is not work , do I  missed something?

Thanks

**Comment by kylekirkby** [comment]
Currently supported plugins for Github Pages can be found here - https://pages.github.com/versions/

I do not think they have allowed for use of this plugin yet.

**Comment by heshuhua** [comment]
Oh, thanks, 
It's so sad they don't allowed it.
