### ISSUE TITLE
Does this plugin support _data pagination?

### ISSUE THREAD

**Issue by elkcl** [sverrirs/jekyll-paginate-v2#96]
I want to paginate not only cycling through posts, but also through `_data` files. Is it possible with this plugin? If so, how? If not, I'd love to see this feature added.

**Comment by bmann** [comment]
According to #86 it is not possible with this plugin.

**Comment by zelkor** [comment]
Oh, that's a pity. Are there any plugins that have such functionality?

**Comment by bmann** [comment]
I’m not aware of one. Likely needs a custom plugin built — since data files are totally custom.
